sudo: true
language: node_js
node_js: '10'
os: osx
osx_image: xcode10.1

branches:
  only:
  - master

install:
  - npm install
  - npm run webpack2

script:
  - "./node_modules/.bin/build --config ./electron-builder.yml --mac -p always"
